name: Nightly upstream tests
on:
  issue_comment:
    types: [created]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ${{ vars.RUNNER_NORMAL || 'ubuntu-latest' }}

    steps:
      - name: Run Integration Tests
        id: integration_tests
        run: |
          echo "Hello?"

